apiVersion: v1
kind: PersistentVolume
metadata:
  name: graphdb-volume
  labels:
    app.kubernetes.io/name: NODC
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 4Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: nodc-graphdb-claim
    namespace: default
  hostPath:
    path: /data/graphdb/
    type: DirectoryOrCreate
