apiVersion: v1
kind: PersistentVolume
metadata:
  name: linkedpipes-volume
  labels:
    app.kubernetes.io/name: NODC
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 256Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: nodc-linkedpipes-claim
    namespace: default
  hostPath:
    path: /data/linkedpipes/
    type: DirectoryOrCreate
