apiVersion: v1
kind: PersistentVolume
metadata:
  name: website-volume
  labels:
    app.kubernetes.io/name: NODC
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 128Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: nodc-website-claim
    namespace: default
  hostPath:
    path: /data/website/
    type: DirectoryOrCreate
