apiVersion: v1
kind: Service
metadata:
  name: nodc-graphdb
  labels:
    app.kubernetes.io/name: NODC
    app.kubernetes.io/component: graphdb
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: NODC
    app.kubernetes.io/component: graphdb
  ports:
  - protocol: TCP
    targetPort: 7200
    port: 7200

