apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodc-graphdb-pvc
  namespace: nodc
  labels:
    app.kubernetes.io/name: nodc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: oci-block-high
  resources:
    requests:
      storage: 16Gi
