apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodc-graphdb-claim
  labels:
    app.kubernetes.io/name: NODC
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
  selector:
    matchLabels:
      app.kubernetes.io/name: NODC
