



apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodc-graphdb-deployment
  labels:
    app.kubernetes.io/name: NODC
    app.kubernetes.io/component: graphdb
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: NODC
      app.kubernetes.io/component: graphdb
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: NODC
        app.kubernetes.io/component: graphdb
    spec:
      volumes:
        - name: nodc-graphdb-volume
          persistentVolumeClaim:
            claimName: nodc-graphdb-claim
      containers:
        - name: nodc-graphdb
          image: xrgk8s.projekty.ms.mff.cuni.cz:18079/sknodc_graphdb
          imagePullPolicy: Always
          ports:
            - containerPort: 8087
          volumeMounts:
            - mountPath: "/opt/graphdb/home"
              name: nodc-graphdb-volume
