apiVersion: v1
kind: Service
metadata:
  name: nodc-executor
  labels:
    app.kubernetes.io/name: NODC
    app.kubernetes.io/component: linkedpipes.executor
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: NODC
    app.kubernetes.io/component: linkedpipes.executor
  ports:
  - protocol: TCP
    targetPort: 8085
    port: 8085

