apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodc-executor-monitor-deployment
  labels:
    app.kubernetes.io/name: nodc
    app.kubernetes.io/component: linkedpipes.executor-monitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nodc
      app.kubernetes.io/component: linkedpipes.executor-monitor
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nodc
        app.kubernetes.io/component: linkedpipes.executor-monitor
    spec:
      securityContext:
        fsGroup: 5987
      volumes:
        - name: nodc-executor-monitor-volume
          persistentVolumeClaim:
            claimName: nodc-linkedpipes-claim
      containers:
        - name: nodc-linkedpipes-executor-monitor
          image: linkedpipes/etl-executor-monitor:main
          imagePullPolicy: Always
          env:
            - name: LP_ETL_DOMAIN
              value: "http://localhost:8080"
            - name: LP_ETL_EXECUTOR_URL
              value: "http://nodc-executor:8085"
            - name: LP_ETL_EXECUTION_HISTORY_COUNT_LIMIT
              value: "3"
          ports:
            - containerPort: 8081
          volumeMounts:
            - mountPath: "/data/lp-etl/"
              name: nodc-executor-monitor-volume
          securityContext:
            runAsUser: 5987
            runAsGroup: 5987
            runAsNonRoot: true
      initContainers:
        - name: set-data-ownership
          image: alpine:3.17.0
          command: ["chown", "5987:5987", "/data/lp-etl/"]
          volumeMounts:
            - mountPath: "/data/lp-etl/"
              name: nodc-executor-monitor-volume
---
apiVersion: v1
kind: Service
metadata:
  name: nodc-executor-monitor
  labels:
    app.kubernetes.io/name: nodc
    app.kubernetes.io/component: linkedpipes.executor-monitor
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nodc
    app.kubernetes.io/component: linkedpipes.executor-monitor
  ports:
  - protocol: TCP
    targetPort: 8081
    port: 8081

