apiVersion: v1
kind: Service
metadata:
  name: nodc-executor-monitor
  labels:
    app.kubernetes.io/name: NODC
    app.kubernetes.io/component: linkedpipes.executor-monitor
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: NODC
    app.kubernetes.io/component: linkedpipes.executor-monitor
  ports:
  - protocol: TCP
    targetPort: 8081
    port: 8081

