apiVersion: v1
kind: Service
metadata:
  name: nodc-frontend
  labels:
    app.kubernetes.io/name: NODC
    app.kubernetes.io/component: linkedpipes.frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: NODC
    app.kubernetes.io/component: linkedpipes.frontend
  ports:
  - protocol: TCP
    targetPort: 8080
    port: 8080
