apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodc-frontend-deployment
  namespace: nodc
  labels:
    app.kubernetes.io/name: nodc
    app.kubernetes.io/component: linkedpipes.frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nodc
      app.kubernetes.io/component: linkedpipes.frontend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nodc
        app.kubernetes.io/component: linkedpipes.frontend
    spec:
      containers:
        - name: nodc-linkedpipes-frontend
          image: linkedpipes/etl-frontend:main
          imagePullPolicy: Always
          env:
            - name: LP_ETL_DOMAIN
              value: "http://localhost:8080"
            - name: LP_ETL_MONITOR_URL
              value: "http://nodc-executor-monitor:8081"
            - name: LP_ETL_STORAGE_URL
              value: "http://nodc-storage:8083"
          ports:
            - containerPort: 8080
          securityContext:
            runAsUser: 5987
            runAsGroup: 5987
            runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: nodc-frontend
  labels:
    app.kubernetes.io/name: nodc
    app.kubernetes.io/component: linkedpipes.frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nodc
    app.kubernetes.io/component: linkedpipes.frontend
  ports:
  - protocol: TCP
    targetPort: 8080
    port: 8080
