apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodc-linkedpipes-storage-pvc
  labels:
    app.kubernetes.io/name: nodc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 4Gi
  volumeName: nodc-storage-pv
