apiVersion: v1
kind: Service
metadata:
  name: nodc-storage
  labels:
    app.kubernetes.io/name: NODC
    app.kubernetes.io/component: linkedpipes.storage
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: NODC
    app.kubernetes.io/component: linkedpipes.storage
  ports:
  - protocol: TCP
    targetPort: 8083
    port: 8083

