apiVersion: v1
kind: Service
metadata:
  name: nodc-registration-updater
  labels:
    app.kubernetes.io/name: NODC
    app.kubernetes.io/component: registration-updater
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: NODC
    app.kubernetes.io/component: registration-updater
  ports:
  - protocol: TCP
    targetPort: 80
    port: 8086
