apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodc-registration-claim
  labels:
    app.kubernetes.io/name: NODC
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      app.kubernetes.io/name: NODC
