# https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/
apiVersion: batch/v1
kind: CronJob
metadata:
  name: nodc-scheduler-cronjob
  labels:
    app.kubernetes.io/name: NODC
    app.kubernetes.io/component: scheduler
spec:
  schedule: "17 2,13 * * *"
  # https://crontab.guru/
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: nodc-linkedpipes-volume
              persistentVolumeClaim:
                claimName: nodc-linkedpipes-claim      
          containers:
          - name: nodc-linkedpipes-executor
            image: ghcr.io/datova-kancelaria/sk_nodc_scheduler:latest
            imagePullPolicy: Always
            env:
              - name: STORAGE_REPOSITORY
                value: "https://github.com/datova-kancelaria/nkod-pipeline.git"
              - name: RELOAD_URL
                value: "http://nodc-storage:8083/api/v1/management/reload"
              - name: EXECUTE_PIPELINE_URL
                value: "http://nodc-frontend:8080/api/v1/executions?pipeline=https://sk-nkod.opendata.cz/etl/resources/pipelines/1651823973959"
            volumeMounts:
              - mountPath: "/data/lp-etl/"
                name: nodc-linkedpipes-volume
          restartPolicy: OnFailure
