apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodc-website-pvc
  labels:
    app.kubernetes.io/name: nodc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 64Gi
  volumeName: nodc-website-pv
