apiVersion: v1
kind: Service
metadata:
  name: nodc-website
  labels:
    app.kubernetes.io/name: NODC
    app.kubernetes.io/component: website
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: NODC
    app.kubernetes.io/component: website
  ports:
  - protocol: TCP
    targetPort: 8090
    port: 8090
    nodePort: 31000
