apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodc-website-deployment
  labels:
    app.kubernetes.io/name: nodc
    app.kubernetes.io/component: website
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nodc
      app.kubernetes.io/component: website
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nodc
        app.kubernetes.io/component: website
    spec:
      volumes:
        - name: nodc-website-volume
          persistentVolumeClaim:
            claimName: nodc-website-pvc
      containers:
        - name: nodc-website
          image: ghcr.io/datova-kancelaria/nodc_website:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          volumeMounts:
            - mountPath: "/data/website/"
              name: nodc-website-volume
