# https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/
apiVersion: batch/v1
kind: CronJob
metadata:
  name: nodc-certificate-manager-cronjob
  namespace: nodc
  labels:
    app.kubernetes.io/name: nodc
    app.kubernetes.io/component: certificate-manager
spec:
  # https://crontab.guru/
  # Keep in mind this is server (k8s provide) time not your time. 
  # There is beta feature to plan using Time zones yet not in stable:
  # https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#time-zones
  # By default the time is in UTC+0
  schedule: "0 1 1 */3 *"  
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          labels:
            app.kubernetes.io/name: nodc
            app.kubernetes.io/component: certificate-manager
          volumes:
            - name: nginx-certs
              secret:
                name: nodc-https
          containers:
            - name: certbot
              image: certbot/certbot:v2.2.0
              command: ["certonly"]
              args: ["--cert-path", "/opt/letsencrypt/tls.crt", "--key-path", "/opt/letsencrypt/tls.ket"]
              imagePullPolicy: Always
              ports:
                - containerPort: 80
              volumeMounts:
                - name: nginx-certs
                  mountPath: /opt/letsencrypt/
          restartPolicy: Never
