apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodc-certificate-pv
  namespace: nodc
  labels:
    app.kubernetes.io/name: nodc
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: nodc
    name: nodc-certificate-pvc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: fss.csi.oraclecloud.com
    volumeHandle: # {NODC-Website-OCID}:{MountTargetIP}:/certificate
