apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodc-linkedpipes-storage-pv
  namespace: nodc
  labels:
    app.kubernetes.io/name: nodc
spec:
  capacity:
    storage: 256Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: nodc
    name: nodc-linkedpipes-storage-pvc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: fss.csi.oraclecloud.com
    volumeHandle: # {NODC-LinkedPipes-Storage-OCID}:{MountTargetIP}:/linkedpipes-storage
