# https://docs.oracle.com/en-us/iaas/Content/Block/Concepts/blockvolumeperformance.htm
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: oci-block-balanced
  namespace: nodc
  labels:
    app.kubernetes.io/name: nodc
provisioner: blockvolume.csi.oraclecloud.com
parameters:
  vpusPerGB: "10"
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
