apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodc-linkedpipes-executor-pvc
  namespace: nodc
  labels:
    app.kubernetes.io/name: nodc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: oci-block-balanced
  resources:
    requests:
      storage: 256Gi
