apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodc-website-deployment
  namespace: nodc
  labels:
    app.kubernetes.io/name: nodc
    app.kubernetes.io/component: website
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nodc
      app.kubernetes.io/component: website
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nodc
        app.kubernetes.io/component: website
    spec:
      volumes:
        - name: nodc-website-volume
          persistentVolumeClaim:
            claimName: nodc-website-pvc
        - name: nginx-configs
          configMap:
            name: nodc-nginx
            items:
              - name: website.nginx
                path: default.yaml
        - name: nginx-certs
          secret:
            name: nodc-https
      containers:
        - name: nodc-website
          image: ghcr.io/datova-kancelaria/nodc_website:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - mountPath: "/data/website/"
              name: nodc-website-volume
            - name: nginx-configs
              mountPath: /etc/nginx/conf.d/
            - name: nginx-certs
              mountPath: /etc/nginx/certs/

  