name: docker
on:
  push:
    branches:
      - 'main'
jobs:
  publish-docker:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Publish scheduler
        uses: docker/build-push-action@v3
        with:
          context: ./components/scheduler/
          push: true
          tags: ghcr.io/datova-kancelaria/nodc_scheduler:latest
      -
        name: Publish registration-updater
        uses: docker/build-push-action@v3
        with:
          context: ./components/registration-updater/
          push: true
          tags: ghcr.io/datova-kancelaria/nodc_registration_updater:latest
      -
        name: Publish website
        uses: docker/build-push-action@v3
        with:
          context: ./components/website/
          push: true
          tags: ghcr.io/datova-kancelaria/nodc_website:latest
