name: publish-manager
on:
  push:
    paths:
      - "components/manager/**"
    branches:
      - 'main'
      - 'develop'
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Publish manager
        uses: docker/build-push-action@v3
        with:
          context: ./components/manager/
          push: true
          tags: ghcr.io/datova-kancelaria/nodc_manager:${{ github.ref_name }}
